// <auto-generated />
namespace TravelManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _FinalSettlementCtx_ReqDet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_FinalSettlementCtx_ReqDet));
        
        string IMigrationMetadata.Id
        {
            get { return "202405221200558__FinalSettlementCtx_ReqDet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
