// <auto-generated />
namespace TravelManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _FSapprovalCtx_v2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_FSapprovalCtx_v2));
        
        string IMigrationMetadata.Id
        {
            get { return "202404010105573__FSapprovalCtx_v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
